# put those values in a `secrets.toml` file
ean_frontend = ""
cdn_root = ""

[telegram_config]
bot_token = ""
maintainer_ids = [0]

[api_config]
api_root = ""
brand_name = ""
module_version = ""
promo_sync_api_version = ""
