# put those values in a `secrets.toml` file
[telegram_config]
bot_token = ""
maintainer_ids = [0]

[api_config]
api_root = ""
brand_name = ""
anonymous_csrf = ""
legal_ids = [""]
module_version = ""
sms_api_version = ""
next_step_version = ""
create_account_version = ""
login_api_version = ""
promo_sync_api_version = ""